const jwt = require("jsonwebtoken");
const config = require("../config/key");
const {promisify} = require("util");
// SignIn token generator.
/**
 *
 * @returns {String,String} - Token: for authentication and ExpiredIn: The time at which the token will be expired.
 */
exports.signToken = (id) => {
  
	return jwt.sign({
		id: id
	}, config.jwtSecret, {expiresIn: config.jwtExpiresIn});
};
/**
 * Verify that the token is generated by this system.
 *
 * @param {String} token  - Authentication token provided from user.
 * @returns {String} Id /null  - if user with the provided token exists it will return user id else it will return null
 */

exports.getUserId = async (token) => {
	const {id, iat} = await promisify(jwt.verify)(token, config.jwtSecret);
	return id;
};
